server:
  servlet:
    context-path: /springboot
  port: 9999
    # 使用默认的数据库连接池配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtdb?characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: /mybatis/mappers/*.xml
  type-aliases-package: com.chinasoft.springboot.demo.pojo



#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/testdemo?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 182838
#    type: com.alibaba.druid.pool.DruidDataSource
#    #最大活跃数
#    maxActive: 20
#    #初始化数量
#    initialSize: 1
#    #最大连接等待超时时间
#    maxWait: 60000
#    #打开PSCache，并且指定每个连接PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
#    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1 from dual
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
#    filters: stat, wall, log4j